// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esffuetokbrbdhqgsyqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzZmZ1ZXRva2JyYmRocWdzeXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNTUzMTcsImV4cCI6MjA5MTgzMTMxN30.FTwxOvwVVPfB_4--00yc1QyBPysrq8lehTT3faW4SPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});